# These are supported funding model platforms

github: jibran # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: jibran
open_collective: jibran
ko_fi: jibran
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: jibran
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
