title: S.T.O.R.E.
logo: /android-chrome-512x512.png
email: jibran.ijaz@gmail.com
author:
  name: Jibran Ijaz
  twitter: JibranIjaz
twitter:
  username: JibranIjaz
  card: summary
social:
  name: Jibran Ijaz
  links:
    - https://twitter.com/JibranIjaz
    - https://www.linkedin.com/in/JibranIjaz
    - https://github.com/jibran
    - https://keybase.io/jibran
webmaster_verifications:
  google: 3rWLfKwbv6FbbpPlf2gEQm7UTrtknNf3fioGA0wDMLg
  bing: 5901F7ABEF3E85BFB5BBCF9755A1EF17
copyright: Copyright © 2021
description: >- # this means to ignore newlines until "baseurl:"
  A personal website to share
  suggestions, thoughts, opinions,
  recommendations, and expressions by
  Jibran Ijaz
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://store.jibran.life" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "/favicon.ico" # the favicon for your site

# Yat date format
yat:
  date_format: "%b %d, %Y"

# Google analytics
#enableDNT: false
google_analytics: UA-188471448-1

# If you want to generate website sitemap, you can set true
sitemap: true

# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
translate_langs:
  - lang: en
    text: English

  - lang: ur
    img: https://www.countryflags.io/pk/flat/64.png
    text: Urdu

# Gitment comments
gitment:
  username: "jibran"
  repo: "jibran.github.io"
  client_id: "cbe660bf526b76932ea5"
  client_secret: "4c31ea3cd9cf03fd6e508f11a27b389c3c747a9f"
  redirect_uri: "https://store.jibran.life"

# Build settings
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM

theme: jekyll-theme-yat

feed:
  excerpt_only: true
#  categories:
#    - drupal
  tags:
    only:
      - drupal_planet

permalink: :title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-redirect-from

exclude:
  - .idea
  - README.md
